# Generated by Django 4.0 on 2021-12-17 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp02', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='board_idx',
            new_name='board',
        ),
    ]
