# Generated by Django 4.0 on 2021-12-21 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp03', '0002_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('tmef', models.CharField(max_length=100)),
                ('wf', models.CharField(max_length=100)),
                ('tmn', models.CharField(max_length=100)),
                ('tmx', models.CharField(max_length=100)),
            ],
        ),
    ]
