# Generated by Django 4.0 on 2021-12-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp03', '0003_forecast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='tmef',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='tmn',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='tmx',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='wf',
            field=models.TextField(null=True),
        ),
    ]
