# Generated by Django 4.0 on 2021-12-22 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp03', '0004_alter_forecast_tmef_alter_forecast_tmn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_Ticktings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=100)),
                ('moviegrade', models.IntegerField(default=0)),
                ('movieReser', models.IntegerField(default=0)),
                ('moviedate', models.CharField(max_length=100)),
            ],
        ),
    ]
