# Generated by Django 4.0 on 2021-12-22 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp03', '0006_alter_movie_ticktings_moviereser_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie_Ticktings',
        ),
    ]
