# Generated by Django 4.0 on 2021-12-22 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp03', '0007_delete_movie_ticktings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_Ticktings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=100)),
                ('moviegrade', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('movieReser', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('moviedate', models.CharField(max_length=100)),
            ],
        ),
    ]
